# .github/workflows/ci.yml
name: RSpec Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      kafka:
        image: bitnami/kafka:latest
        ports:
          - 9092:9092
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
          KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
          ALLOW_PLAINTEXT_LISTENER: "yes"
      zookeeper:
        image: bitnami/zookeeper:latest
        ports:
          - 2181:2181

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2' # or your version

    - name: Install dependencies
      run: |
        bundle install

    - name: create db
      run: |
        rails db:create

    - name: migrate db
      run: |
        rails db:migrate

    - name: Run tests
      env:
        KAFKA_BROKERS: localhost:9092
      run: |
        bundle exec rspec
